export const CHATS_ACTIONS = {
  SET_ACTIVE_CHAT: 'SET_ACTIVE_CHAT',
  DELETE_CHAT: 'DELETE_CHAT',
  SEND_MESSAGE: 'SEND_MESSAGE',
  MARK_AS_READ: 'MARK_AS_READ',
  MARK_AS_PAID: 'MARK_AS_PAID',
  GET_BITCOIN_DATA: 'GET_BITCOIN_DATA',
  SET_BITCOIN_TO_USD_FLOAT: 'SET_BITCOIN_TO_USD_FLOAT',
};
